---
title: "p8105_hw3_jc5929"
output: github_document
date: "2022-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Question 2**

```{r q2}
library(tidyverse) 
library(ggridges) 
library(patchwork) 
library(dplyr)
library(knitr)
accel_data=read_csv("data/accel_data.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    activity_1:activity_1440,
    names_to = 'activity_min',
    values_to = 'activity_count',
    names_prefix = 'activity_'
  )  %>%
mutate(activity_count=round(activity_count,2)) %>%
  mutate(day_type=
        case_when(
     day== 'Monday' ~ 'weekday',
     day== 'Tuesday' ~ 'weekday',
     day== 'Wednesday' ~ 'weekday',
     day== 'Thursday' ~ 'weekday',
     day== 'Friday' ~ 'weekday',
     day== 'Saturday' ~ 'weekend',
     day== 'Sunday' ~ 'weekend')
   )
accel_data %>%
  group_by(day_id) %>%
  summarize(n_obs=n(),
            total_activity=sum(activity_count)) %>%
  knitr::kable()

  accel_data %>%
  group_by(week) %>%
  ggplot(aes(x=activity_min,y=activity_count,color=day_id))+
  geom_line()+geom_point(alpha=0.3)+viridis::scale_color_viridis(name='day_id')
```

**Question 3**
```{r}
library(p8105.datasets) 
data("ny_noaa")
ny_data= ny_noaa %>%
  janitor::clean_names() %>%
  mutate(date=as.character(date)) %>%
  separate(date,into=c('year','month','date'),sep='-') %>%
  mutate(tmax=as.numeric(tmax),tmin=as.numeric(tmin))

jan_plot= 
    ny_data %>%
  filter(month=='01') %>%
  drop_na(tmax) %>%
  group_by(year,id) %>%
  summarize(tmax_average=mean(tmax)) %>%
  ggplot(aes(x=year,y=tmax_average))+geom_point(color='steelblue')

jul_plot=ny_data %>%
  mutate(month=as.character(month)) %>%
  filter(month=='07') %>%
  drop_na(tmax) %>%
  group_by(year,id) %>%
  summarize(tmax_average=mean(tmax)) %>%
  ggplot(aes(x=year,y=tmax_average))+geom_point(color='pink')

jan_plot+jul_plot

plot1= ny_data %>%
    ggplot(aes(x=tmin,y=tmax))+geom_hex()
  
plot2 = ny_data %>%
    filter(snow>0 & snow<100) %>%
    group_by(year) %>%
    summarize(snowfall=sum(snow)) %>%
    ggplot(aes(x=year,y=snowfall))+geom_col(color='steelblue')
 
plot1+plot2




```